# Generated by Django 5.1.7 on 2025-03-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetails',
            name='pdf_theme',
            field=models.CharField(choices=[('theme1', 'Classic (Theme 1)'), ('theme2', 'Modern Minimalist (Theme 2)'), ('theme3', 'Bold Corporate (Theme 3)')], default='theme1', max_length=20),
        ),
    ]
