# Generated by Django 5.1.7 on 2025-03-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_shopdetails_pdf_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Alert when stock falls below this', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current stock quantity', max_digits=10),
        ),
    ]
