# Generated by Django 5.1.7 on 2025-03-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_product_low_stock_threshold_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
