# Generated by Django 5.1.7 on 2025-03-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_customer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_stock_level',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum stock level for alerts', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current stock level', max_digits=10),
        ),
    ]
